add npm publish
MetaMask/action-publish-release pull request #43
Opened 2022-01-27 00:30 UTC by rickycodes

re: #2 

I've tested this out in my fork of controllers: https://github.com/rickycodes/controllers/runs/4959663731?check_suite_focus=true

2022-01-27 00:39 UTC, rickycodes commented on action.yml
> +        cache: 'npm'
I actually don't think this is required. I'll test without tomorrow

2022-01-27 17:10 UTC, rickycodes commented on action.yml
> +    required: true
we may want to change this up. my thinking is this would be used primarily for libraries, but if we want to use this for clients as well then this would have to be optional

2022-01-27 18:11 UTC, rekmarks commented on action.yml
> +    required: true
It's fine for now, I think!

2022-01-27 18:15 UTC, rekmarks requested changes
The `publish-release` workflow in the module template repository should be updated with whatever changes ultimately land here.

2022-01-27 18:15 UTC, rekmarks commented on action.yml
> +      run: ${{ github.action_path }}/scripts/yarn-setup.sh
This step and `yarn-setup.sh` should be deleted. The following lines should be added to the `publish-release` workflow to ensure that everything is set up properly:
- https://github.com/MetaMask/metamask-module-template/blob/2c22a6b1622cc37b71631e7891701b09bb02a3c6/.github/workflows/build-test.yml#L16-L34
- https://github.com/MetaMask/metamask-module-template/blob/2c22a6b1622cc37b71631e7891701b09bb02a3c6/.github/workflows/build-test.yml#L43-L49

2022-01-28 20:21 UTC, rekmarks commented on scripts/npm-publish.sh
> +npm publish
```suggestion
if [[ -z $NPM_TOKEN ]]; then
  echo "Notice: NPM_TOKEN environment variable not set. Skipping npm publishing."
else
  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  npm publish
fi
```

2022-01-28 20:21 UTC, rekmarks commented on action.yml
> +    required: true
```suggestion
    required: false
```

2022-01-28 20:22 UTC, rekmarks commented on action.yml
> +    description: 'The token used for npm publishing'
```suggestion
    description: 'The token used for npm publishing. Publishing to npm will be skipped if omitted.'
```

2022-01-28 20:24 UTC, rekmarks commented on action.yml
> +      run: ${{ github.action_path }}/scripts/yarn-setup.sh
the `publish-release` workflow in _all repositories where we want to publish to npm_*

Most especially, we should do this in the module template repository.

2022-01-28 20:34 UTC, rickycodes commented
Ok! I think this should be good meow

2022-01-28 21:13 UTC, rekmarks approved these changes
LGTM!

2022-01-28 21:33 UTC, rickycodes commented on scripts/npm-publish.sh
> +if [[ -z $NPM_TOKEN ]]; then
There's a caveat here which is this will still be `false` if `NPM_TOKEN` is set but it's empty... which I don't think we want. Say for instance we set up `controllers` to use this and somebody accidentally deletes the secret then this will just happily skip publishing which I don't we don't want?

I think ideally we'd want to `exit 1` for that case.

idk, maybe it's fine?

now I am thinking about adding another job that checks to ensure the version that's published can be pulled down and verified :roll_eyes:

2022-02-08 22:23 UTC, rekmarks commented on scripts/npm-publish.sh
> +if [[ -z $NPM_TOKEN ]]; then
I think it's fine. We'll notice if things aren't getting published. The `NPM_TOKEN` should also be an org-wide secret, so deleting it should be very difficult.

2022-02-08 22:27 UTC, merged